apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-api
spec:
  selector:
    matchLabels:
      app: database-api
  template:
    metadata:
      labels:
        app: database-api
    spec:
      containers:
      - name: database-api
        image: localhost:32000/equity-api:1.0.2 
        #imagePullPolicy: IfNotPresent # don't go to internet, check locally
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 5500
