apiVersion: v1
kind: Service
metadata:
  name: database-api
spec:
  selector:
    app: database-api
  ports:
  - name: api
    port: 5500 # service port 
    targetPort: 5500 # where api listnes 
  - name: pprof
    port: 6060 
    targetPort: 6060